### ISSUE TITLE
react-spring issue

### ISSUE THREAD

**Issue by joglr** [git-truck/git-truck#278]
Uncaught (in promise) Error: The arity of each "output" value must be equal
    at react-spring-shared.esm.js:651:1
    at Array.map (<anonymous>)
    at react-spring-shared.esm.js:649:1
    at Array.map (<anonymous>)
    at createStringInterpolator (react-spring-shared.esm.js:649:1)
    at createInterpolator (react-spring-shared.esm.js:451:1)
    at AnimatedString.reset (react-spring-animated.esm.js:126:1)
    at SpringValue._start (react-spring-core.esm.js:1333:1)
    at SpringValue._merge (react-spring-core.esm.js:1233:1)
    at onStart (react-spring-core.esm.js:434:1)

**Comment by joglr** [comment]
This may be the cause of 

- [ ] Sometimes colors persist through different metrics
