### ISSUE TITLE
Analyser error, ref_type: branch-metadata, is invalid

### ISSUE THREAD

**Issue by jjdonov** [git-truck/git-truck#559]
Please describe your idea / problem below:

I am trying to start git-truck following the readme. After running `npx git-truck@latest`, my browser launches and shows this error page:

![CleanShot 2022-05-06 at 10 29 52](https://user-images.githubusercontent.com/6962027/167182737-2921cbe5-d28f-4967-8a65-b74b2fca4eec.png)

```
Analyser error, ref_type: branch-metadata, is invalid
Error: Analyser error, ref_type: branch-metadata, is invalid
    at Function.parseRefs (/Users/johndonovan/.npm/_npx/bc50e1a49926e12f/node_modules/git-truck/build/index.js:2739:17)
    at Function.getRepoMetadata (/Users/johndonovan/.npm/_npx/bc50e1a49926e12f/node_modules/git-truck/build/index.js:2657:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 40)
    at Function.scanDirectoryForRepositories (/Users/johndonovan/.npm/_npx/bc50e1a49926e12f/node_modules/git-truck/build/index.js:2704:24)
    at loader2 (/Users/johndonovan/.npm/_npx/bc50e1a49926e12f/node_modules/git-truck/build/index.js:7370:32)
    at Object.callRouteLoader (/Users/johndonovan/.npm/_npx/bc50e1a49926e12f/node_modules/@remix-run/server-runtime/data.js:77:14)
```

**terminal output:**
```
Need to install the following packages:
  git-truck@latest
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
(node:72983) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Git Truck version 1.0.3 (latest)

Now listening on port 3000
Opening http://localhost:3000 in your browser
There was an error running the data loader for route routes/index
GET / 500 - - 3595.633 ms
```

| dependency | version |
|-|-|
| git | 2.34.0 |
| node | 16.13.1 |
| npm | 8.1.2 |

**Comment by jjdonov** [comment]
Thank you @joglr and @tjomson ! Can confirm that its working after #560

**Comment by tjomson** [comment]
> Thank you @joglr and @tjomson ! Can confirm that its working after #560 

@jjdonov great to hear! Thanks for reporting the issue
