### ISSUE TITLE
FR: create a precanned docker recipie for git-truck

### ISSUE THREAD

**Issue by stsquad** [git-truck/git-truck#564]
As the node requirement is higher than most distros pack it falls over :

```
✗  docker run --rm -it -u (id -u) -v $HOME:$HOME -w (pwd) alex:git-truck /usr/bin/fish 
Using Emacs in /home/alex/src/emacs/install 
Welcome to fish, the friendly interactive shell                                       
🕙16:17:05 alex@721bc49521ae:qemu.git  on  virtio/virtio-cleanups-and-gpio-v2 [$!?⇡] 
➜  npx git-truck@latest
Need to install the following packages:                                               
  git-truck@latest                                                                    
Ok to proceed? (y) y 
npm WARN EBADENGINE Unsupported engine {                                              
npm WARN EBADENGINE   package: 'git-truck@1.0.14',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.5', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated 
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path  
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path
npm WARN tar TAR_ENTRY_INFO stripping / from absolute path
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
/home/alex/.npm/_npx/bc50e1a49926e12f/node_modules/git-truck/build/index.js:2478
  const groups = (match == null ? void 0 : match.groups) ?? {};
                                                          ^           
                                                                                      
SyntaxError: Unexpected token '?'                                                     
    at wrapSafe (internal/modules/cjs/loader.js:915:16)               
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)        
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)                 
    at Object.<anonymous> (/home/alex/.npm/_npx/bc50e1a49926e12f/node_modules/git-truck/cli.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)         
npm ERR! code 1
npm ERR! path /home/alex/lsrc/qemu.git
npm ERR! command failed
npm ERR! command sh -c git-truck
```

Using the container definition:

```
#
ARG USER
FROM node:current-bullseye-slim

# Duplicate deb line as deb-src
RUN cat /etc/apt/sources.list | sed "s/^deb\ /deb-src /" >> /etc/apt/sources.list

# Install common build utilities
RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -yy eatmydata
RUN DEBIAN_FRONTEND=noninteractive eatmydata \
    apt install -y --no-install-recommends \
        fish \
        git \
        zile

# The build script sets USER/UID so we can easily map to the host environment.
ARG USER
ARG UID

# Add the user hardcoded
RUN useradd -u ${UID} -U ${USER}

WORKDIR /usr/app
RUN npm install git-truck
```

For ease of evaluation it might be worth packaging up a docker container yourself (or at least providing a tested recipe).

**Comment by joglr** [comment]
Thank you for this interesting use case! 

We might be able to reduce the required node requirement by adjusting the browserBuildTarget in our build step.

**Comment by mircealungu** [comment]
The idea of @stsquad is nice. 
For those who have docker but don't have node, a docker container would be a welcome solution!

**Comment by mircealungu** [comment]
Ah! Today I learned that [`` `command` `` has been deprecated for `$(command)`](https://stackoverflow.com/a/4708569/1200070). Thanks :)

**Comment by mircealungu** [comment]
@joglr @stsquad @hojelse is this a new thing? now i get the same error when running outside of docker. indeed, why isn't the system creating the temp folder in the current working folder? 

    ✖ Error writing data to file /usr/local/lib/node_modules/git-truck/.temp/TypeScript/main.json

**Comment by joglr** [comment]
> @joglr @stsquad @hojelse is this a new thing? now i get the same error when running outside of docker. indeed, why isn't the system creating the temp folder in the current working folder?
> 
> ```
> ✖ Error writing data to file /usr/local/lib/node_modules/git-truck/.temp/TypeScript/main.json
> ```

I have not seen this error occur before. We could investigate a better place to place temporary files. Node.js have a built-in way of detecting this.

**Comment by joglr** [comment]
I have created the issue: #596 which should fix the tempdir issue.

**Comment by joglr** [comment]
I have changed the location of the cache to the os tempdir in #598 

Please let me know if it solved the issue by trying the experimental release with docker.

**Comment by mircealungu** [comment]
Hmm. I'm trying to run the new version from docker, but it crashes with:

```
Git Truck version 0.0.0-5464416 [!] Update available: 1.2.0

To update, run:

npx git-truck@latest

Or to install globally:

npm install -g git-truck@latest


Starting Git Truck...

Application available at http://localhost:3000

Opening in your browser...
Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

```

Since it crashes on "opening in your browser" I wonder whether the solution would be that you give me a --headless CLI option that does not try to open the browser anymore?

**Comment by joglr** [comment]
Oh, interesting. Keep it simple, we should just be failing gracefully and maybe print "Unable to open in browser automatically, here's the link.

**Comment by mircealungu** [comment]
Good point :)

**Comment by joglr** [comment]
@stsquad This is now released!
