### ISSUE TITLE
Error/crash when analyzing repo

### ISSUE THREAD

**Issue by iuliand-db** [git-truck/git-truck#591]
Using Chrome Version 106.0.5249.91 (Official Build) (arm64)

The repo is large (17000+ files, 2.7 million lines of ocde).

```An error occured!
See console for more infomation.

Error
    at K6 (http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:109:48330)
    at id (http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:109:48027)
    at fd (http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:109:50514)
    at http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:109:51459
    at Jr.Rf [as eachAfter] (http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:109:45822)
    at i (http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:109:50964)
    at g4 (http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:157:1417)
    at http://localhost:3000/build/routes/$repo.$-62JXSMTE.js:143:184
    at Object.useMemo (http://localhost:3000/build/_shared/chunk-Y7FU7OLJ.js:5:58719)
    at N.useMemo (http://localhost:3000/build/_shared/chunk-YDCVFN7Q.js:1:7509)
[Retry](http://localhost:3000/runtime)
[Go back](http://localhost:3000/)
```

And in the JS Console:

```
Error
    at K6 ($repo.$-62JXSMTE.js:109:48330)
    at id ($repo.$-62JXSMTE.js:109:48027)
    at fd ($repo.$-62JXSMTE.js:109:50514)
    at $repo.$-62JXSMTE.js:109:51459
    at Jr.Rf [as eachAfter] ($repo.$-62JXSMTE.js:109:45822)
    at i ($repo.$-62JXSMTE.js:109:50964)
    at g4 ($repo.$-62JXSMTE.js:157:1417)
    at $repo.$-62JXSMTE.js:143:184
    at Object.useMemo (chunk-Y7FU7OLJ.js:5:58719)
    at N.useMemo (chunk-YDCVFN7Q.js:1:7509)
ui @ chunk-Y7FU7OLJ.js:7
$repo.$-62JXSMTE.js:259 
qM @ $repo.$-62JXSMTE.js:259
$repo.$-62JXSMTE.js:259 Error
    at K6 ($repo.$-62JXSMTE.js:109:48330)
    at id ($repo.$-62JXSMTE.js:109:48027)
    at fd ($repo.$-62JXSMTE.js:109:50514)
    at $repo.$-62JXSMTE.js:109:51459
    at Jr.Rf [as eachAfter] ($repo.$-62JXSMTE.js:109:45822)
    at i ($repo.$-62JXSMTE.js:109:50964)
    at g4 ($repo.$-62JXSMTE.js:157:1417)
    at $repo.$-62JXSMTE.js:143:184
    at Object.useMemo (chunk-Y7FU7OLJ.js:5:58719)
    at N.useMemo (chunk-YDCVFN7Q.js:1:7509)
qM @ $repo.$-62JXSMTE.js:259
```

**Comment by joglr** [comment]
Hello, thanks for reporting this issue!

This is a known issue, already open at #576, so I will close this one, but thanks for providing further details!
