### ISSUE TITLE
Crash when trying to sortCommits

### ISSUE THREAD

**Issue by joglr** [git-truck/git-truck#668]
https://github.com/git-truck/git-truck/blob/main/src/components/FileHistoryElement.tsx#L134

```
$repo.$-U5IXKV3A.js:16337 TypeError: Cannot read properties of undefined (reading 'time')
    at $repo.$-U5IXKV3A.js:12610:44
    at Array.map (<anonymous>)
    at sortCommits ($repo.$-U5IXKV3A.js:12609:13)
    at CommitDistFragment ($repo.$-U5IXKV3A.js:12517:27)
    at renderWithHooks (chunk-GUPKMWBY.js:12191:26)
    at updateFunctionComponent (chunk-GUPKMWBY.js:14597:28)
    at beginWork (chunk-GUPKMWBY.js:15932:22)
    at beginWork$1 (chunk-GUPKMWBY.js:19769:22)
    at performUnitOfWork (chunk-GUPKMWBY.js:19214:20)
    at workLoopSync (chunk-GUPKMWBY.js:19153:13)
```

**Comment by dawidwoz** [comment]
I will fix it when I add the sorting option (currently no available) with the next pull request.

**Comment by joglr** [comment]
> I will fix it when I add the sorting option (currently no available) with the next pull request. 

That is good to hear! I have linked this issue to your PR, correct me if it is the wrong PR.
