### ISSUE TITLE
Error: Invariant failed is logged to the console

### ISSUE THREAD

**Issue by reichni** [git-truck/git-truck#762]
Please describe your idea / problem below:
When I run `npx -y git-truck` within the folder of my repository I get the following:

```
Git Truck version 1.14.1 (latest)

✔ App started 1ms
✔ Done checking for git repo 35ms
✔ Opened Git Truck in your browser 5ms
✔ Found branch head 17ms
✔ Commit tree analyzed 21ms
✔ Commit tree hydrated 32ms
✔ Wrote data to /var/folders/80/tptw8tr14ll8tl8sqskngh8r0000gn/T/git-truck/myproject-backend/main.json 1ms
✔ Ready in 161ms
No sorted authors for file myproject-backend/.env.example
No sorted authors for file myproject-backend/src/contact/__init__.py
No sorted authors for file myproject-backend/src/contact/migrations/__init__.py
No sorted authors for file myproject-backend/src/organization/migrations/__init__.py
No sorted authors for file myproject-backend/src/points/__init__.py
No sorted authors for file myproject-backend/src/points/migrations/__init__.py
No sorted authors for file myproject-backend/src/poll/migrations/__init__.py
No sorted authors for file myproject-backend/src/subscription/__init__.py
No sorted authors for file myproject-backend/src/subscription/migrations/__init__.py
No sorted authors for file myproject-backend/src/users/migrations/__init__.py
No sorted authors for file myproject-backend/src/wait_list/migrations/__init__.py
SYSTEM
Error: Invariant failed
    at z6 (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/build/index.js:84:109948)
    at Cp1 (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/build/index.js:94:8824)
    at Pk (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:119:4230)
    at a.loader (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:119:5446)
    at p (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:113:13360)
    at JR (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:113:13794)
    at /Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:113:11582
    at Array.map (<anonymous>)
    at u (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:113:11575)
    at c (/Users/me/.npm/_npx/b7d9c0e931d6d7c6/node_modules/git-truck/cli.js:113:9714)
```

I'm running this on my macOS Sequoia 15.0.1 with Command Line Tools 16.0.0.0.1.1724870825 installed if this is of any importance.

**Comment by joglr** [comment]
Hi! Thanks for reporting this.

Does Git Truck still open in your browser?

**Comment by joglr** [comment]
Okay, thank you. This is a known error that you can look on past, as it does not affect the user experience. I will keep the issue open, so we can make sure the error is not logged to the console.

**Comment by reichni** [comment]
Ah okay, sorry I couldn't find this in the list of issues. But thank you for your information.

**Comment by waldowred5** [comment]
I also get the same error as above. However after opening the browser the app never makes it beyond the loading screen:

Version: `Git Truck version 2.0.2 (latest)`
macOS: `Sequoia 15.2 (24C101)`

![Image](https://github.com/user-attachments/assets/c548d799-d3c8-4097-8f3b-18d15e149220)

**Comment by nimrossum** [comment]
> I also get the same error as above. However after opening the browser the app never makes it beyond the loading screen:
> 
> Version: `Git Truck version 2.0.2 (latest)`
> macOS: `Sequoia 15.2 (24C101)`
> Browser: `Google Chrome Version 132.0.6834.84 (Official Build) (arm64)`
> 
> ![Image](https://github.com/user-attachments/assets/c548d799-d3c8-4097-8f3b-18d15e149220)

Can you also provide the Node.js version used?

**Comment by last-Programmer** [comment]
i also get this error and it does not go part starting analysis. my node version is 22.11.0

**Comment by nimrossum** [comment]
> i also get this error and it does not go past starting analysis. my node version is 22.11.0

Can you provide some more details?

OS 
Repository that you are analyzing
Are you on the latest Git Truck version?

**Comment by darkskygit** [comment]
same problem

os: macOS
repo: https://github.com/FFmpeg/FFmpeg
node: 20.11.1

latest version of git truck

**Comment by nimrossum** [comment]
Try going to localhost:3000 and click Clear analyzed results and see if it helps.

**Comment by darkskygit** [comment]
> Try going to localhost:3000 and click Clear analyzed results and see if it helps.

this work fine for me

**Comment by nimrossum** [comment]
I have created an issue specifically for the app freeze problem: #783 
This issue is about invariant failed specifically, which is not an issue itself that prevents the app from being used.
